
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - nodered.nerden.de.github.com
  resources:
  - nodereds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodered.nerden.de.github.com
  resources:
  - nodereds/finalizers
  verbs:
  - update
- apiGroups:
  - nodered.nerden.de.github.com
  resources:
  - nodereds/status
  verbs:
  - get
  - patch
  - update
